"""Real managed-runtime smoke test for release CI; no OS service registration."""
import json
import os
from pathlib import Path
import subprocess
import socket
import sys
import tempfile
import time
import urllib.request

with tempfile.TemporaryDirectory(prefix='Etna space ') as temporary:
    config = Path(temporary) / 'René tools'
    kits = config / 'kits'
    kits.mkdir(parents=True)
    (kits / '__init__.py').write_bytes('# Auto-generated by Etna CLI — old\n'.encode('cp1252'))
    (kits / 'smoke.py').write_text(
        'from utils import tool\n'
        '@tool\ndef echo(text: str) -> str:\n    """Echo Unicode text."""\n    return text\n',
        encoding='utf-8',
    )
    env = {**os.environ, 'ETNA_CONFIG_DIR': str(config), 'PYTHONIOENCODING': 'utf-8'}
    with socket.socket() as listener:
        listener.bind(('127.0.0.1', 0))
        env['ETNA_SMOKE_PORT'] = str(listener.getsockname()[1])
    command = [sys.executable, '-c',
               "import os; from etna import server_manager as sm; "
               "sm.BASE_PORT = int(os.environ['ETNA_SMOKE_PORT']); "
               "from etna.cli import main; main()"]
    try:
        subprocess.run(command + ['start'], env=env, check=True, timeout=180)
        compile((kits / '__init__.py').read_bytes(), str(kits / '__init__.py'), 'exec')
        port = json.loads((config / 'config.json').read_text(encoding='utf-8'))['port']
        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
        with opener.open(f'http://localhost:{port}/health', timeout=10) as response:
            assert json.load(response)['service'] == 'etna-mcp'
        # The initiating CLI has exited. Verify the background process remains
        # healthy well beyond the reported few-second Windows shutdown.
        for _ in range(20):
            time.sleep(1)
            with opener.open(f'http://localhost:{port}/health', timeout=5) as response:
                assert json.load(response)['service'] == 'etna-mcp'
        request = {'jsonrpc': '2.0', 'id': 1, 'method': 'tools/call',
                   'params': {'name': 'echo', 'arguments': {'text': 'café 工具'}}}
        result = subprocess.run(command + ['start', 'stdio'], input=json.dumps(request)+'\n',
                                env=env, text=True, encoding='utf-8', capture_output=True,
                                check=True, timeout=30)
        payload = json.loads(result.stdout)
        assert 'error' not in payload, payload
        assert 'café 工具' in json.dumps(payload, ensure_ascii=False), payload
        print('Managed runtime, legacy encoding repair, UTF-8 path, health and MCP verified.')
    finally:
        subprocess.run(command + ['stop'], env=env, timeout=30)
    if sys.platform == 'win32':
        # Exercise the exact pythonw service launcher without registering a task
        # on the runner. Pythonw has different standard-stream behavior.
        from unittest.mock import patch
        from etna import server_manager as manager
        with patch.object(manager.cfg, 'CONFIG_DIR', config), patch.object(manager, '_windows_user_sid', return_value='S-1-5-21-123'), patch.object(manager, '_run_checked'), patch.object(manager.subprocess, 'run'):
            manager._install_task_scheduler(config / 'venv' / 'Scripts' / 'python.exe')
        launcher = config / 'service_launcher.py'
        launcher.write_text(launcher.read_text(encoding='utf-8').replace(
            'run_server_supervised()', f'run_server_supervised(port={port})'), encoding='utf-8')
        service = subprocess.Popen(
            [str(config / 'venv' / 'Scripts' / 'pythonw.exe'), str(launcher)],
            env=env, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL, creationflags=0x08000000,
        )
        try:
            for _ in range(60):
                try:
                    with opener.open(f'http://localhost:{port}/health', timeout=1) as response:
                        assert json.load(response)['service'] == 'etna-mcp'
                    break
                except OSError:
                    if service.poll() is not None:
                        raise RuntimeError('pythonw launcher exited before becoming healthy')
                    time.sleep(0.25)
            else:
                raise RuntimeError('pythonw launcher health timeout')
            for _ in range(20):
                time.sleep(1)
                with opener.open(f'http://localhost:{port}/health', timeout=5) as response:
                    assert json.load(response)['service'] == 'etna-mcp'
            assert 'Application startup complete' in (config / 'service.log').read_text(encoding='utf-8')
            assert 'Server child started:' in (config / 'lifecycle.log').read_text(encoding='utf-8')
            print('Windowless pythonw service launcher, real log handles and 20-second health verified.')
        finally:
            subprocess.run(command + ['stop'], env=env, timeout=30)
            if service.poll() is None:
                service.terminate()
            service.wait(timeout=15)
