"""Real managed-runtime smoke test for release CI; no OS service registration."""
import json
import os
from pathlib import Path
import subprocess
import socket
import sys
import tempfile
import urllib.request

with tempfile.TemporaryDirectory(prefix='Etna space ') as temporary:
    config = Path(temporary) / 'René tools'
    kits = config / 'kits'
    kits.mkdir(parents=True)
    (kits / '__init__.py').write_bytes('# Auto-generated by Etna CLI — old\n'.encode('cp1252'))
    (kits / 'smoke.py').write_text(
        'from utils import tool\n'
        '@tool\ndef echo(text: str) -> str:\n    """Echo Unicode text."""\n    return text\n',
        encoding='utf-8',
    )
    env = {**os.environ, 'ETNA_CONFIG_DIR': str(config), 'PYTHONIOENCODING': 'utf-8'}
    with socket.socket() as listener:
        listener.bind(('127.0.0.1', 0))
        env['ETNA_SMOKE_PORT'] = str(listener.getsockname()[1])
    command = [sys.executable, '-c',
               "import os; from etna import server_manager as sm; "
               "sm.BASE_PORT = int(os.environ['ETNA_SMOKE_PORT']); "
               "from etna.cli import main; main()"]
    try:
        subprocess.run(command + ['start'], env=env, check=True, timeout=180)
        compile((kits / '__init__.py').read_bytes(), str(kits / '__init__.py'), 'exec')
        port = json.loads((config / 'config.json').read_text(encoding='utf-8'))['port']
        opener = urllib.request.build_opener(urllib.request.ProxyHandler({}))
        with opener.open(f'http://localhost:{port}/health', timeout=10) as response:
            assert json.load(response)['service'] == 'etna-mcp'
        request = {'jsonrpc': '2.0', 'id': 1, 'method': 'tools/call',
                   'params': {'name': 'echo', 'arguments': {'text': 'café 工具'}}}
        result = subprocess.run(command + ['start', 'stdio'], input=json.dumps(request)+'\n',
                                env=env, text=True, encoding='utf-8', capture_output=True,
                                check=True, timeout=30)
        payload = json.loads(result.stdout)
        assert 'error' not in payload, payload
        assert 'café 工具' in json.dumps(payload, ensure_ascii=False), payload
        print('Managed runtime, legacy encoding repair, UTF-8 path, health and MCP verified.')
    finally:
        subprocess.run(command + ['stop'], env=env, timeout=30)
