import contextlib
import io
import json
import subprocess
import tempfile
import unittest
import xml.etree.ElementTree as ET
from pathlib import Path
from unittest.mock import Mock, patch

from etna import config as cfg, server_manager as sm, cli


class WindowsCompatibilityTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory(prefix='Etna space ')
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name) / 'René & tools'
        self.root.mkdir()
        for name, value in {
            'CONFIG_DIR': self.root, 'CONFIG_FILE': self.root / 'config.json',
            'KITS_DIR': self.root / 'kits', 'VENV_DIR': self.root / 'venv',
            'PID_FILE': self.root / 'server.pid',
        }.items():
            patcher = patch.object(cfg, name, value)
            patcher.start()
            self.addCleanup(patcher.stop)

    def test_reproduces_and_repairs_cp1252_generated_source(self):
        cfg.KITS_DIR.mkdir()
        init = cfg.KITS_DIR / '__init__.py'
        init.write_bytes('# Auto-generated by Etna CLI — do not delete.\n'.encode('cp1252'))
        with self.assertRaises(UnicodeDecodeError):
            init.read_bytes().decode("utf-8")
        cfg.kits_dir()
        compile(init.read_bytes(), str(init), 'exec')
        self.assertIn('—', init.read_text(encoding='utf-8'))

    def test_custom_initializer_preserved(self):
        cfg.KITS_DIR.mkdir()
        init = cfg.KITS_DIR / '__init__.py'
        init.write_text('# custom\n', encoding='utf-8')
        cfg.kits_dir()
        self.assertEqual(init.read_text(), '# custom\n')

    def test_shim_replaces_legacy_encoded_file(self):
        shim = self.root / 'utils.py'
        shim.write_bytes('# Etna utils shim — old\n'.encode('cp1252'))
        with patch.object(sm, '_venv_site_packages', return_value=self.root):
            sm._write_utils_shim()
        compile(shim.read_bytes(), str(shim), 'exec')

    def test_utf8_json_and_bom(self):
        cfg.CONFIG_FILE.write_text(json.dumps({'kits': {'café': {'kit_name': '工具'}}}, ensure_ascii=False), encoding='utf-8-sig')
        config = cfg.load()
        cfg.save(config)
        self.assertEqual(cfg.load(), config)
        self.assertFalse(cfg.CONFIG_FILE.read_bytes().startswith(b'\xef\xbb\xbf'))

    def test_runtime_unicode_path_uses_utf8_pipe(self):
        with patch.object(sm.subprocess, 'run', return_value=Mock(stdout=str(self.root)+'\n')) as run:
            self.assertEqual(sm._venv_site_packages(), self.root)
        self.assertEqual(run.call_args.kwargs['encoding'], 'utf-8')
        self.assertEqual(run.call_args.kwargs['env']['PYTHONIOENCODING'], 'utf-8')

    def test_task_xml_and_launcher_preserve_configuration(self):
        captured = {}
        def checked(command, **kwargs):
            if '/Create' in command:
                captured['xml'] = Path(command[command.index('/XML') + 1]).read_text(encoding='utf-16')
            return Mock(returncode=0)
        with patch.object(sm, '_windows_user_sid', return_value='S-1-5-21-123'), patch.object(sm, '_run_checked', side_effect=checked), patch.object(sm.subprocess, 'run'), contextlib.redirect_stdout(io.StringIO()):
            sm._install_task_scheduler(self.root / 'venv' / 'Scripts' / 'python.exe')
        doc = ET.fromstring(captured['xml'])
        ns = {'t': 'http://schemas.microsoft.com/windows/2004/02/mit/task'}
        self.assertTrue(doc.find('.//t:Command', ns).text.endswith('pythonw.exe'))
        self.assertEqual(doc.find('.//t:WorkingDirectory', ns).text, str(self.root.resolve()))
        self.assertEqual(doc.find('.//t:ExecutionTimeLimit', ns).text, 'PT0S')
        self.assertEqual(doc.find('.//t:LogonType', ns).text, 'InteractiveToken')
        launcher = self.root / 'service_launcher.py'
        compile(launcher.read_bytes(), str(launcher), 'exec')
        self.assertIn(repr(str(self.root.resolve())), launcher.read_text(encoding='utf-8'))
        self.assertIn('service.log', launcher.read_text(encoding='utf-8'))
        self.assertFalse((self.root / '_etna_task.xml').exists())

    def test_background_windows_detaches_without_verbose_detach(self):
        with patch.object(sm.sys, 'platform', 'win32'):
            self.assertEqual(sm._background_process_options()['creationflags'], 0x08000200)
            self.assertEqual(sm._background_process_options(True), {})

    def test_failed_start_never_saves_success(self):
        with patch.object(cli.cfg, 'load', return_value={}), patch.object(cli.cfg, 'save') as save, patch.object(sm, 'start_server', side_effect=RuntimeError('failure')), contextlib.redirect_stderr(io.StringIO()):
            with self.assertRaises(SystemExit) as error:
                cli.cmd_start([])
        self.assertEqual(error.exception.code, 1)
        save.assert_not_called()

    def test_early_child_failure_cleans_pid_and_keeps_diagnostics(self):
        process = Mock(pid=123)
        process.poll.return_value = 1
        def launch(*args, **kwargs):
            kwargs['stderr'].write(b'SyntaxError: broken source\n')
            kwargs['stderr'].flush()
            return process
        with patch.object(sm, '_port_open', return_value=False), patch.object(sm, 'ensure_venv'), patch.object(sm.subprocess, 'Popen', side_effect=launch), contextlib.redirect_stdout(io.StringIO()):
            with self.assertRaisesRegex(RuntimeError, 'broken source'):
                sm.start_server({})
        self.assertFalse(cfg.PID_FILE.exists())
        self.assertIn('broken source', (self.root / 'server.log').read_text())
        process.wait.assert_called_once()

    def test_roaming_client_paths_honor_appdata(self):
        with patch.object(cli.sys, 'platform', 'win32'), patch.dict(cli.os.environ, {'APPDATA': str(self.root)}):
            self.assertEqual(cli._claude_config_path(), self.root / 'Claude' / 'claude_desktop_config.json')
            self.assertEqual(cli._vscode_config_path(), self.root / 'Code' / 'User' / 'settings.json')

    def test_client_entry_refreshes_launcher_after_upgrade(self):
        path = self.root / 'mcp.json'
        path.write_text(json.dumps({'mcpServers': {'Web': {'command': 'etna', 'args': ['start', 'stdio', 'web']}}}), encoding='utf-8')
        executable = str(self.root / 'etna.exe')
        with patch.object(cli, '_etna_executable', return_value=executable):
            cli._write_stdio_config(path, 'mcpServers', {'kits': {'web': {'kit_name': 'Web'}}}, silent=True)
        self.assertEqual(json.loads(path.read_text())['mcpServers']['Web']['command'], executable)

    def test_supervisor_records_native_exit_codes_and_bounds_restarts(self):
        child = Mock(pid=456)
        child.wait.return_value = 0xC0000005
        child.poll.return_value = 0xC0000005
        with patch.object(sm.subprocess, 'Popen', return_value=child) as launch, patch.object(sm.time, 'sleep'):
            self.assertEqual(sm.run_server_supervised(port=9876), 0xC0000005)
        log = (self.root / 'lifecycle.log').read_text(encoding='utf-8')
        self.assertIn('hex=0xC0000005', log)
        self.assertIn('stopped after four unexpected exits', log)
        self.assertEqual(launch.call_count, 4)
        self.assertIs(launch.call_args.kwargs['stdout'], sm.sys.stdout)
        self.assertIs(launch.call_args.kwargs['stderr'], sm.sys.stderr)
        self.assertEqual(launch.call_args.kwargs['env']['PYTHONFAULTHANDLER'], '1')
        self.assertFalse(cfg.PID_FILE.exists())

    def test_foreground_logs_clean_shutdown_without_overwriting_supervisor_pid(self):
        cfg.PID_FILE.write_text('555', encoding='ascii')
        with patch.dict(sm.os.environ, {'ETNA_SUPERVISED': '1'}), patch('uvicorn.run') as run:
            sm.run_server_foreground(port=9876)
        self.assertEqual(cfg.PID_FILE.read_text(), '555')
        log = (self.root / 'lifecycle.log').read_text(encoding='utf-8')
        self.assertIn('Server starting:', log)
        self.assertIn('Server leaving run loop:', log)
        self.assertEqual(run.call_args.kwargs['log_level'], 'info')

    def test_foreground_retains_exception_before_propagating(self):
        with patch('uvicorn.run', side_effect=RuntimeError('server failure')):
            with self.assertRaisesRegex(RuntimeError, 'server failure'):
                sm.run_server_foreground()
        self.assertIn('server failure', (self.root / 'lifecycle.log').read_text(encoding='utf-8'))
        self.assertFalse(cfg.PID_FILE.exists())


if __name__ == '__main__':
    unittest.main()
