"""
etna/config.py — Config file management

Config lives at:
  Linux/macOS: ~/.etna_server/config.json
  Windows:     %APPDATA%\\Etna\\config.json

Tracks:
  - kits:   { kit_stem: { "kit_name": str, "kit_description": str, "enabled": bool } }
  - port:   int | null         (main server port, always 8467)

Per-kit config lives at <CONFIG_DIR>/kit_configs/<kit_stem>/config.json
and is read directly by the server at runtime.

Skills:
  Kit skills:     <CONFIG_DIR>/kit_skills/<kit_stem>/   (paired with a kit, served via inspect_kit)
  General skills: <CONFIG_DIR>/skills/<skill_name>/     (standalone, served via list_skills)
  Each skill folder contains SKILL.md plus optional scripts/, references/, assets/.
"""

import json
import os
import sys
from pathlib import Path


def _default_config_dir() -> Path:
    # Allow override via env var so the venv's uvicorn process finds the right dir
    env_override = os.environ.get("ETNA_CONFIG_DIR")
    if env_override:
        return Path(env_override)
    if sys.platform == "win32":
        appdata = os.environ.get("APPDATA")
        if appdata:
            return Path(appdata) / "Etna"
        return Path.home() / "AppData" / "Roaming" / "Etna"
    return Path.home() / ".etna_server"


CONFIG_DIR      = _default_config_dir()
CONFIG_FILE     = CONFIG_DIR / "config.json"
KITS_DIR        = CONFIG_DIR / "kits"
KIT_CONFIGS_DIR = CONFIG_DIR / "kit_configs"
KIT_SKILLS_DIR  = CONFIG_DIR / "kit_skills"
SKILLS_DIR      = CONFIG_DIR / "skills"
VENV_DIR        = CONFIG_DIR / "venv"
CHROME_PROFILE  = CONFIG_DIR / "chrome-profile"
PID_FILE        = CONFIG_DIR / "server.pid"
CHROME_PID_FILE = CONFIG_DIR / "chrome.pid"

DEFAULT_CONFIG = {
    "kits":  {},
    "port":  None,
}


def load() -> dict:
    """Load config from disk, creating defaults if absent."""
    if not CONFIG_FILE.exists():
        save(DEFAULT_CONFIG.copy())
        return DEFAULT_CONFIG.copy()
    with open(CONFIG_FILE) as f:
        data = json.load(f)
    for key, val in DEFAULT_CONFIG.items():
        data.setdefault(key, val)
    return data


def save(config: dict):
    """Write config to disk atomically."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    tmp = CONFIG_FILE.with_suffix(".tmp")
    with open(tmp, "w") as f:
        json.dump(config, f, indent=2)
    os.replace(tmp, CONFIG_FILE)


def kits_dir() -> Path:
    """Return the managed kits directory, creating it if absent."""
    KITS_DIR.mkdir(parents=True, exist_ok=True)
    init = KITS_DIR / "__init__.py"
    if not init.exists():
        init.write_text(
            "# Auto-generated by Etna CLI — do not delete.\n"
            "import importlib, pkgutil, pathlib\n\n"
            "def _auto_import_kits():\n"
            "    package_dir = pathlib.Path(__file__).resolve().parent\n"
            "    for finder, module_name, is_pkg in pkgutil.iter_modules([str(package_dir)]):\n"
            "        if module_name.startswith('_'):\n"
            "            continue\n"
            "        importlib.import_module(f'.{module_name}', package=__name__)\n\n"
            "_auto_import_kits()\n"
        )
    return KITS_DIR


def kit_skills_dir() -> Path:
    """Return the kit skills directory, creating it if absent."""
    KIT_SKILLS_DIR.mkdir(parents=True, exist_ok=True)
    return KIT_SKILLS_DIR


def kit_skill_path(kit_stem: str) -> Path:
    """Return the skill folder path for a specific kit."""
    return KIT_SKILLS_DIR / kit_stem


def skills_dir() -> Path:
    """Return the general skills directory, creating it if absent."""
    SKILLS_DIR.mkdir(parents=True, exist_ok=True)
    return SKILLS_DIR


def skill_path(skill_name: str) -> Path:
    """Return the folder path for a general skill."""
    return SKILLS_DIR / skill_name


def kit_configs_dir() -> Path:
    """Return the kit configs directory, creating it if absent."""
    KIT_CONFIGS_DIR.mkdir(parents=True, exist_ok=True)
    return KIT_CONFIGS_DIR


def kit_config_path(kit_stem: str) -> Path:
    """Return the config.json path for a specific kit."""
    path = KIT_CONFIGS_DIR / kit_stem
    path.mkdir(parents=True, exist_ok=True)
    return path / "config.json"


def load_kit_config(kit_stem: str) -> dict:
    """Load the saved config values for a kit. Returns {} if not set."""
    path = kit_config_path(kit_stem)
    if not path.exists():
        return {}
    with open(path) as f:
        return json.load(f)


def save_kit_config(kit_stem: str, values: dict):
    """Write config values for a kit atomically."""
    path = kit_config_path(kit_stem)
    tmp = path.with_suffix(".tmp")
    with open(tmp, "w") as f:
        json.dump(values, f, indent=2)
    os.replace(tmp, path)


CLIENTS_FILE = CONFIG_DIR / "clients.json"


def load_clients() -> dict:
    """Load the registered client registry. Returns {} if not set."""
    if not CLIENTS_FILE.exists():
        return {}
    with open(CLIENTS_FILE) as f:
        return json.load(f)


def save_clients(clients: dict):
    """Write the client registry to disk atomically."""
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    tmp = CLIENTS_FILE.with_suffix(".tmp")
    with open(tmp, "w") as f:
        json.dump(clients, f, indent=2)
    os.replace(tmp, CLIENTS_FILE)


def register_client(name: str, data: dict):
    """Add or update a client entry in the registry."""
    clients = load_clients()
    clients[name] = data
    save_clients(clients)


def unregister_client(name: str):
    """Remove a client from the registry."""
    clients = load_clients()
    clients.pop(name, None)
    save_clients(clients)
